# Generated by Django 4.2 on 2023-04-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SandImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('coin_diameter', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
                ('status', models.IntegerField()),
            ],
        ),
    ]
