# Generated by Django 4.2 on 2023-04-09 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_currency_code', models.CharField(max_length=3)),
                ('coin_name', models.CharField(max_length=10)),
                ('coin_length', models.FloatField()),
                ('coin_error', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SandImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('coin_type', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
