# Generated by Django 4.2 on 2023-04-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandimage',
            name='coin_diamater',
            field=models.FloatField(),
        ),
    ]
