# Generated by Django 4.2 on 2023-04-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandimage',
            name='coin_type',
            field=models.CharField(max_length=20),
        ),
    ]
