# Generated by Django 4.2 on 2023-04-17 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0002_alter_sandimage_coin_diamater'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sandimage',
            old_name='coin_diamater',
            new_name='coin_diameter',
        ),
    ]
